SELECT SUM(MYR_MAARA)
FROM MYYNTPER
LEFT JOIN MYYNTRIV ON MYP_MYYNTINRO=MYR_MYYNTINRO
LEFT JOIN TUOTPER ON MYR_TUOTEKOODI=TP_TUOTEKOODI AND MYR_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE MYP_PVM BETWEEN '2019-1-1' AND '2019-5-31'
AND MYR_MAARA > 0
AND TP_TOIMITTAJANRO = 400
AND TP_ALEKOODI IN (1460)
