SELECT TP_TUOTEKOODI, TP_NIMI, TV_VARASTOSSA, SUM(TV_MYYTY_KPL_V1 + TV_MYYTY_KPL_V2 + TV_MYYTY_KPL_V3) AS KOLME_AASTA_MYYK
FROM TUOTPER
LEFT JOIN TUOTVAIH ON TP_TUOTEKOODI = TV_TUOTEKOODI AND TP_TOIMITTAJANRO = TV_TOIMITTAJANRO
WHERE TP_TOIMITTAJANRO = 124 AND TV_VARASTOSSA > 0 AND TP_TUOTEKOODI NOT LIKE '%DEP%'
GROUP BY TP_TUOTEKOODI, TP_NIMI, TV_VARASTOSSA, TV_MYYTY_KPL_V1, TV_MYYTY_KPL_V2, TV_MYYTY_KPL_V3
ORDER BY TP_TUOTEKOODI ASC