SELECT TP_TUOTEKOODI, TP_NIMI, TP_MYYNTIHINTA, SUM(TV_VARASTOSSA)
FROM TUOTPER
LEFT JOIN TUOTVAIH ON TP_TUOTEKOODI = TV_TUOTEKOODI AND TP_TOIMITTAJANRO = TV_TOIMITTAJANRO
WHERE TP_TUOTEKOODI IN (SELECT TP_TUOTEKOODI FROM TUOTPER WHERE TP_TOIMITTAJANRO = 363) AND
TV_VARASTOSSA > 0
GROUP BY TP_TUOTEKOODI, TP_NIMI, TP_MYYNTIHINTA