SELECT TP_ALEKOODI, SUM(OTR_TOIMITETTUMAARA) AS AASTA_OST
FROM TUOTPER
INNER JOIN OSTOTILRIV ON TP_TUOTEKOODI = OTR_TUOTEKOODI AND TP_TOIMITTAJANRO = OTR_TOIMITTAJANRO
INNER JOIN OSTOTIL ON OT_NRO = OTR_NRO
WHERE (TP_TOIMITTAJANRO = 124)
AND OT_SAAPUMISAIKA BETWEEN '2019-1-1' AND '2019-10-1'
GROUP BY TP_ALEKOODI
