SELECT MYR_TUOTEKOODI, TP_NIMI, SUM(MYR_MAARA) AS MYYDUD_TK
FROM MYYNTPER
LEFT JOIN MYYNTRIV ON MYP_MYYNTINRO=MYR_MYYNTINRO
LEFT JOIN TUOTPER ON MYR_TUOTEKOODI=TP_TUOTEKOODI AND MYR_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE MYP_PVM BETWEEN '2016-3-1' AND '2019-3-1' AND MYP_ASIAKASNRO = 10400
AND MYR_RIVISUMMA > 0
GROUP BY MYR_TUOTEKOODI, TP_NIMI
ORDER BY MYYDUD_TK DESC