SELECT AP_ASIAKASNRO, AP_NIMI, ASR_ASIAKRYHMKOODI, ARY_NIMI, AP_MAAKOODI, AP_VASTUUHLO
FROM ASIAKPER
LEFT JOIN ASIAKKAANRYHM ON AP_ASIAKASNRO = ASR_ASIAKASNRO
LEFT JOIN ASIAKRYH ON ASR_ASIAKRYHMKOODI = ARY_KOODI
WHERE ASR_ASIAKRYHMKOODI LIKE 'IL%' AND ASR_ASIAKRYHMKOODI NOT LIKE 'ILT%'