SELECT MYR_TUOTEKOODI, TP_NIMI, SUM(MYR_MAARA), SUM(MYR_RIVISUMMA)
FROM MYYNTPER
LEFT JOIN MYYNTRIV ON MYP_MYYNTINRO=MYR_MYYNTINRO
LEFT JOIN TUOTPER ON MYR_TUOTEKOODI=TP_TUOTEKOODI AND MYR_TOIMITTAJANRO = TP_TOIMITTAJANRO
LEFT JOIN ASIAKALE ON ASA_TUOTEKOODI = TP_TUOTEKOODI AND ASA_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE MYP_PVM BETWEEN '2019-3-1' AND '2019-3-31'
AND (ASA_ALKUPVM = '2019-3-1' AND ASA_LOPPUPVM = '2019-3-31')
AND MYR_RIVISUMMA > 0
--AND MYR_MYYJAKOODI NOT IN (601, 602)
--AND MYR_MYYJAKOODI IN (601, 602)
GROUP BY MYR_TUOTEKOODI, TP_NIMI