SELECT TP_TOIMITTAJANRO, TP_TUOTEKOODI, TP_NIMI, TP_ALEKOODI, TV_VARASTOSSA, TV_MYYTY_KPL_V1, TV_MYYTY_KPL_V2, (TV_MYYTY_KPL_V1 + TV_MYYTY_KPL_V2), (ROUND(((TV_MYYTY_KPL_V1 + TV_MYYTY_KPL_V2) / TV_VARASTOSSA), 2)) AS SUHE
FROM TUOTPER
INNER JOIN TUOTVAIH ON TP_TUOTEKOODI = TV_TUOTEKOODI AND TP_TOIMITTAJANRO = TV_TOIMITTAJANRO
WHERE TV_VARASTOSSA > 0 AND TV_MYYTY_KPL_V2 > 0
GROUP BY TP_TOIMITTAJANRO, TP_TUOTEKOODI, TP_NIMI, TP_ALEKOODI, TV_VARASTOSSA, TV_MYYTY_KPL_V1, TV_MYYTY_KPL_V2, SUHE
HAVING SUHE < 0.5 AND SUHE > 0   -- LAOSEIS ‹LE KAHE KORRA SUUREM KUI POOLETEISE AASTA M‹‹K KOKKU
ORDER BY SUHE ASC
