SELECT TV_TUOTEKOODI, TP_NIMI, TV_VARASTOSSA, TV_VARASTONARVO, TV_SAAPUU, TV_MYYTY, TV_MYYTY_V1 AS SEE_AASTA, TV_MYYTY_V2 AS EELMINE_AASTA, TV_MYYTY_V3 AS YLE_EELMINE_AASTA, SUM(TV_MYYTY_KPL_V1 + TV_MYYTY_KPL_V2 + TV_MYYTY_KPL_V3) AS KOLME_AASTA_MYYK
FROM TUOTVAIH
LEFT JOIN TUOTPER ON TP_TUOTEKOODI=TV_TUOTEKOODI AND TP_TOIMITTAJANRO=TV_TOIMITTAJANRO
WHERE TV_VIIM_VM <= '2016-7-1'
AND TV_SAAPUU <= '2017-12-31'
AND TV_VARASTOSSA > 0
AND TV_TOIMITTAJANRO NOT IN (679, 678, 684)
AND TP_ALEKOODI NOT IN (1051, 1151, 1351, 1451, 1456, 1461, 1471)
AND (TV_TUOTEKOODI NOT LIKE '%RUNKO' AND TV_TUOTEKOODI NOT LIKE '%DEP')
GROUP BY TV_TUOTEKOODI, TP_NIMI, TV_VARASTOSSA, TV_VARASTONARVO, TV_SAAPUU, TV_MYYTY, TV_MYYTY_V1, TV_MYYTY_V2, TV_MYYTY_V3
ORDER BY TV_TUOTEKOODI ASC