SELECT TP_HYLLYPAIKKA, TP_TUOTEKOODI, TP_TOIMITTAJANRO, TP_NIMI, TP_ALEKOODI, TV_VARASTOSSA, (ROUND((TV_KESKIHINTA * TV_VARASTOSSA / 1.2), 2)) AS LAO_VAARTUS, TV_SAAPUU, TV_MYYTY
FROM TUOTPER
INNER JOIN TUOTVAIH ON TV_TUOTEKOODI = TP_TUOTEKOODI AND TV_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE TP_TOIMITTAJANRO = 400
AND (TV_MYYTY <= '2017-1-1' OR TV_MYYTY IS NULL) AND TV_SAAPUU <= '2017-1-1'
AND TV_VARASTOSSA > 0 
AND TP_ALEKOODI NOT IN (1051, 1151, 1351, 1451, 1456, 1461, 1471)
AND TP_TUOTEKOODI NOT LIKE '%RUNKO'
ORDER BY TP_HYLLYPAIKKA