SELECT MYR_TUOTEKOODI, TP_NIMI, SUM(MYR_MAARA) MYYDUD_TK, ROUND(SUM(MYR_RIVISUMMA/1.2), 2) SUMMA_KMTA, TP_ALEKOODI
FROM MYYNTPER
LEFT JOIN MYYNTRIV ON MYP_MYYNTINRO=MYR_MYYNTINRO
LEFT JOIN TUOTPER ON MYR_TUOTEKOODI=TP_TUOTEKOODI AND MYR_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE MYP_PVM BETWEEN '2019-5-14' AND '2019-5-21'
AND MYR_TUOTEKOODI IN ('1701-1010', '1701-1000', '1701-1005')
GROUP BY MYR_TUOTEKOODI, TP_NIMI, TP_ALEKOODI
ORDER BY MYR_TUOTEKOODI ASC