SELECT TP_TUOTEKOODI, TP_TOIMITTAJANRO, TP_NIMI, TP_ALEKOODI, TV_VARASTOSSA, TP_MYYNTIHINTA, TP_OSTOHINTA, ROUND(TV_KESKIHINTA, 2), ROUND(1 - TV_KESKIHINTA/TP_OSTOHINTA, 2) AS SUHE
FROM TUOTPER
LEFT JOIN TUOTVAIH ON TV_TUOTEKOODI = TP_TUOTEKOODI AND TV_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE TV_KESKIHINTA > 0 AND TP_OSTOHINTA > 0
AND TV_MYYTY > '2019-07-01'
AND TP_ALEKOODI NOT IN (1051, 1151, 1351, 1451, 1456, 1461, 1471)
AND TV_VARASTOSSA != 0
AND ABS(ROUND(1 - TV_KESKIHINTA/TP_OSTOHINTA, 2)) > 0.15
ORDER BY SUHE DESC