SELECT INT_TUOTEKOODI, INT_TOIMITTAJANRO, NK_NIMI, INT_TULLINIMIKEKOODI, INT_YKSIKKOPAINO, INT_VALMISTUSMAA
FROM INTRASTAT
LEFT JOIN NIMIKEKAANNOS ON INT_TUOTEKOODI = NK_TUOTEKOODI AND INT_TOIMITTAJANRO = NK_TOIMITTAJANRO
WHERE INT_TUOTEKOODI NOT LIKE '%DEP%' AND INT_TUOTEKOODI NOT LIKE '%RUNKO%' AND INT_YKSIKKOPAINO > 0 AND NK_NIMI > 0 AND INT_TULLINIMIKEKOODI > 0 AND INT_VALMISTUSMAA > 0 AND INT_TOIMITTAJANRO != 477
ORDER BY INT_TUOTEKOODI