SELECT DISTINCT TP_HYLLYPAIKKA, TP_TUOTEKOODI, TP_NIMI, TV_VARASTOSSA, TP_ALEKOODI, TP_VEROKANTA, TP_OSTOHINTA, TP_MYYNTIHINTA, TV_VARASTONARVO, TP_HALYTYSRAJA, TP_TILAUSMAARA
FROM tuotper LEFT JOIN tuotvaih ON TP_TOIMITTAJANRO=TV_TOIMITTAJANRO AND TP_TUOTEKOODI=TV_TUOTEKOODI
WHERE TP_HYLLYPAIKKA = ''
AND
(TV_VARASTOSSA > 0)
AND
(TP_TUOTEKOODI NOT LIKE '%DEP%' AND TP_TUOTEKOODI NOT LIKE '%RUNKO' AND TP_TUOTEKOODI NOT LIKE '%KOR-DR' AND TP_TUOTEKOODI NOT LIKE '%04R' AND TP_TUOTEKOODI NOT LIKE '%-000R' AND TP_TUOTEKOODI NOT IN ('TAKUUHYVITYS'))
ORDER BY TP_HYLLYPAIKKA DESC, TP_TUOTEKOODI ASC