SELECT AP_ASIAKASNRO, AP_VASTUUHLO
FROM ASIAKPER
WHERE AP_ASIAKASNRO NOT IN (SELECT ASR_ASIAKASNRO FROM ASIAKKAANRYHM WHERE ASR_ASIAKRYHMKOODI LIKE '%SULETUD%')
AND AP_VASTUUHLO != ''
AND AP_VASTUUHLO NOT LIKE '6%' -- FILTER OUT LATVIA
ORDER BY AP_ASIAKASNRO ASC