SELECT MYR_TUOTEKOODI, TP_NIMI, SUM(MYR_MAARA) MYYDUD_TK, ROUND(SUM(MYR_RIVISUMMA/1.2), 2) SUMMA_KMTA
FROM MYYNTPER
LEFT JOIN MYYNTRIV ON MYP_MYYNTINRO=MYR_MYYNTINRO
LEFT JOIN TUOTPER3 ON MYR_TUOTEKOODI=TP_TUOTEKOODI AND MYR_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE MYP_PVM BETWEEN '2018-7-26' AND '2019-7-26'
AND MYR_RIVISUMMA != 0
AND TP_TUOTEKOODI IN (SELECT TP_TUOTEKOODI FROM TUOTPER3 WHERE TP_TOIMITTAJANRO = 518)
/*AND MYR_VEROKANTA = 20*/
GROUP BY MYR_TUOTEKOODI, TP_NIMI, TP_ALEKOODI
ORDER BY MYYDUD_TK DESC