SELECT MYR_TUOTEKOODI, TP_NIMI, SUM(MYR_MAARA) MYYDUD_TK, ROUND(SUM(MYR_RIVISUMMA/1.2), 2) SUMMA_KMTA, TP_ALEKOODI
FROM MYYNTPER
LEFT JOIN MYYNTRIV ON MYP_MYYNTINRO=MYR_MYYNTINRO
LEFT JOIN TUOTPER ON MYR_TUOTEKOODI=TP_TUOTEKOODI AND MYR_TOIMITTAJANRO = TP_TOIMITTAJANRO
WHERE MYP_PVM BETWEEN '2018-1-1' AND '2018-12-31'
AND MYR_RIVISUMMA != 0
AND MYR_TUOTEKOODI > 0
AND MYR_VEROKANTA = 20
GROUP BY MYR_TUOTEKOODI, TP_NIMI, TP_ALEKOODI
ORDER BY MYR_TUOTEKOODI ASC