SELECT TT_TOIMITUSTAPANRO, TT_TOIMITUSTAPA, COUNT(*)
FROM LAHETPER
LEFT JOIN TOIMITUSTAPA ON LTP_TOIMITUSTAPAKOODI = TT_TOIMITUSTAPANRO
WHERE LTP_TOIMITUSTAPAKOODI IN (2, 3, 5, 6, 7)
AND LTP_PVM BETWEEN '2018-7-16' AND '2019-7-16'
GROUP BY TT_TOIMITUSTAPANRO, TT_TOIMITUSTAPA
ORDER BY TT_TOIMITUSTAPANRO ASC