SELECT TP_TUOTEKOODI, SUM(TV_VARASTOSSA), SUM(TV_MYYTY_KPL_V2), SUM(TV_MYYTY_KPL_V3), (SUM(TV_MYYTY_KPL_V2) - SUM(TV_MYYTY_KPL_V3)) AS HALVE
FROM TUOTPER
LEFT JOIN TUOTVAIH ON TP_TUOTEKOODI = TV_TUOTEKOODI AND TP_TOIMITTAJANRO = TV_TOIMITTAJANRO
WHERE TP_TUOTEKOODI IN (SELECT TP_TUOTEKOODI FROM TUOTPER WHERE TP_TOIMITTAJANRO = 124 AND TP_TUOTEKOODI NOT LIKE '%DEP' AND TP_TUOTEKOODI NOT LIKE '%RUNKO') AND (TV_MYYTY_KPL_V2 > 0 OR TV_MYYTY_KPL_V3 > 0)
GROUP BY TP_TUOTEKOODI
ORDER BY HALVE ASC